apiVersion: v1
kind: Namespace
metadata:
  name: simple-web-app
  labels:
    name: simple-web-app


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-deployment
  namespace: simple-web-app
  labels:
    app.kubernetes.io/name: simple-web-app
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-web-app
      app.kubernetes.io/component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-web-app
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: simple-web-app
        image: visdocker11/simpletimeservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        
