apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
  namespace: simple-web-app
spec:
  type: LoadBalancer
  selector:
     app.kubernetes.io/name: simple-web-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP

