name: SimpleWebApp

on:
    push:
        branches:
            - main

jobs:
    # trivy-Scan:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v2
    #           with:
    #                 fetch-depth: 0

    #         - name : Install Trivy
    #           run: |
    #               sudo apt-get install wget apt-transport-https gnupg lsb-release
    #               wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    #               echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    #               sudo apt-get update
    #               sudo apt-get install trivy

            
    #         - name: Run Trivy scan
    #           run: |
    #                  echo "Running Trivy scan..."
    #                  trivy config --exit-code 1 --severity HIGH,CRITICAL --no-progress --quiet --timeout 10m --cache-dir /tmp/trivy-cache ./src/Dockerfile
    
    docker-build:
        runs-on: ubuntu-latest
        # needs: trivy-Scan
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Log in to docker hub 
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: src
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/simpletimeservice:app-${{ github.run_number }}        

    modifygit:
      needs: docker-build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            repository: 'Vishtyagi/STSManifests'
            token: ${{ secrets.GIT_PASSWORD }}

        
        - name: Modify the deployment image
          run: |
            git config user.email "vishal12tyagi1998@gmail.com"
            git config user.name "Vishtyagi"
            sed -i "s+visdocker11/simpletimeservice.*+visdocker11/simpletimeservice:app-$RUN_NUMBER+g" deployment.yaml
            cat deployment.yaml
            git add deployment.yaml
            git commit -m "Updated deployment image by GitHub Actions Job modifygit: ${{ github.run_number }}"
            git push origin main
          env:
            GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            RUN_NUMBER: ${{ github.run_number }}

