name: SimpleWebApp

on:
    push:
        branches:
            - main

jobs:
    trivy-Scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0

            - name : Install Trivy
              run: |
                  echo "Installing Trivy..."
                  sudo apt-get update
                  sudo apt-get install -y trivy
            
            - name: Run Trivy scan
              run: |
                     echo "Running Trivy scan..."
                     trivy config Dockerfile    
    
    docker-build:
        runs-on: ubuntu-latest
        needs: trivy-Scan
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                    fetch-depth: 0
            - name: Log in to docker hub 
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              run: |
                    echo "Building and pushing Docker image..."
                    docker build -t simpletimeservice:latest .
                     
            - name: Push Docker image
              run: |
                    echo "Pushing Docker image..."
                    docker tag simpletimeservice:latest ${{ secrets.DOCKER_USERNAME }}/simpletimeservice:latest
                    docker push ${{ secrets.DOCKER_USERNAME }}/simpletimeservice:latest


     

